---
- name: Installs nginx web server
  apt: pkg=nginx state=installed update_cache=true
  notify:
   - start nginx

- name: Set proxy.conf file
  copy: src=proxy.conf dest=/etc/nginx/conf.d/ mode=0644
  notify:
    - restart nginx
  ignore_errors: True

- name: Remove index.html for host
  file: path=/etc/nginx/sites-enabled/default state=absent
  ignore_errors: True

- name: Remove default conf
  file: path=/etc/nginx/conf.d/default.conf state=absent
  notify:
    - restart nginx
  ignore_errors: True

- name: Creates directory var/log/nginx
  file: path=/var/log/nginx state=directory mode=0777
  sudo: yes