language: node_js
services:
  - mongodb
node_js:
  - '0.12.7'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'wildboard' ]; then cd .. && eval "mv $currentfolder wildboard" && cd wildboard; fi
